name: portfolio
description: A simple Flutter website for my portfolio.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.1
  google_fonts: ^6.1.0
  adaptive_breakpoints: ^0.1.6
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  

flutter:

  uses-material-design: true

  assets:
    - assets/bmw_group_logo.jpeg
    - assets/pimco.jpeg
    - assets/github.png
    - assets/linkedin.png
    - assets/publication.png
    - assets/watch-next.png
    - assets/dentific.png

    
  fonts:
    - family: Julius Sans On
      fonts:
        - asset: fonts/JuliusSansOne-Regular.ttf
